Added supported CPU architecture to README.md
exasol/docker-db pull request #3
Opened 2024-08-30 13:06 UTC by tkilias

2024-08-30 13:12 UTC, ooke submitted a review, later dismissed

2024-08-30 13:29 UTC, rrusinov requested changes
You can also add the SSSE3 requirements, like described here:

https://docs.exasol.com/db/7.1/administration/on-premise/installation/system_requirements.htm

2024-09-05 15:33 UTC, tkilias commented on README.md
> +Exasol currently only support *x86-64* CPUs (Intel64 or AMD64) and is for this architecture optimized.
```suggestion
Exasol currently only supports 64-bit *x86-64* platforms with SSSE3 featured CPUs (Intel64 or AMD64) and is for this architecture optimized. (comparable to Intel Xeon Woodcrest and upwards). See also the [System Requirements](https://docs.exasol.com/db/7.1/administration/on-premise/installation/system_requirements.htm).
```

2024-09-05 15:35 UTC, tkilias commented on README.md
> +Exasol currently only supports 64-bit *x86-64* platforms with SSSE3 featured CPUs (Intel64 or AMD64) and is for this architecture optimized. (comparable to Intel Xeon Woodcrest and upwards). See also
```suggestion
Exasol currently only supports 64-bit *x86-64* platforms with SSSE3 featured CPUs (Intel64 or AMD64) and is for this architecture optimized. See also the [System Requirements](https://docs.exasol.com/db/7.1/administration/on-premise/installation/system_requirements.htm).
```

2024-09-05 16:58 UTC, rrusinov approved these changes

2024-09-05 16:58 UTC, merged